### ISSUE TITLE
Send a periodic heartbeat for every device to Data Updater Plant

### ISSUE THREAD

**Issue by rbino** [astarte-platform/astarte_vmq_plugin#13]
There are some corner cases (e.g. VerneMQ restarts and, while restarting, a device disconnects) where Astarte devices are stuck in the `connected: true` state.

To avoid this, the VerneMQ plugin should send a periodic "heartbeat" to indicate that a device is still connected. DUP will then handle the interruption of the heartbeat as a sign that the device is not connected anymore, and will act accordingly.

**Comment by bettio** [comment]
See also https://github.com/astarte-platform/astarte/issues/304
